### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Donnydada** [ncaanext/NCAA06Next#233]
The link for the textures does not work pls fix it as soon as possible thank you…

**Comment by antdroidx** [comment]
This version is outdated. You should use our latest NCAA NEXT 24. https://download.ncaanext.com

That said, the links are not broken. They are in the Assets section at the bottom of the download pages.

**Comment by Donnydada** [comment]
Thank you very much

**Comment by Donnydada** [comment]
For the PSP?

**Comment by antdroidx** [comment]
We dont support the PSP anymore. You'll need to join their discord for the latest links https://discord.gg/DtfQFvm6d2

**Comment by Donnydada** [comment]
Dang well can I get the ncaa 06 emulator on iPhone ?

**Comment by Donnydada** [comment]
Hey sir uh I am in the discord what to do next?

**Comment by Donnydada** [comment]
Never mind I figured it out thx
